### ISSUE TITLE
Rename files, folders and classes

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#10]
Big refactoring. [Ref: Clean Code]
- [x] Drop Rd prefix
- [x] Mockup -> Mock

**Comment by David-Estevez** [comment]
Also, "Mockup" objects should be called just "Mock"

**Comment by PeterBowman** [comment]
Done at 115fd4e, had to edit a few lines. Please note that the '--mockupXXX' command line options are obsolete, use `--mockXXX`.

**Comment by David-Estevez** [comment]
I'm reopening this as renaming the all classes  directly affects #88

**Comment by PeterBowman** [comment]
@David-Estevez both documentation repos have been already updated, see referenced commits above or:

* asrob-uc3m/robotDevastation-developer-manual@ee0bab0
* asrob-uc3m/robotDevastation-user-manual@c94fe54

**Comment by David-Estevez** [comment]
Ok, then we can close the issue :+1: 

Thanks, @PeterBowman !
