### ISSUE TITLE
Reuniones Robot Devastation (otoño 2017)

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#107]
Por petición popular, se ha creado un Doodle para la próxima reunión.

Aquí el enlace, que también se ha compartido vía Telegram, además de estar en la wiki (portada+página):
https://beta.doodle.com/poll/frq7emqnfisgi7gp

Votación hasta lunes a las 23:55 !!

**Comment by PeterBowman** [comment]
Después de una serie de reuniones previamente votadas vía Doodle y coincidiendo regularmente los viernes a las 17 horas, vamos a fijar este horario como el habitual de aquí en adelante. Enseguida reflejo este hecho en la página de la wiki y dejo un aviso en el grupo de Telegram.
