### ISSUE TITLE
Think about lasers

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#108]
Think about lasers... we used to have Augmented Reality (AR) lasers...

**Comment by jgvictores** [comment]
As commented by @PeterBowman sounds would have to be updated. :-)

**Comment by PeterBowman** [comment]
![giphy](https://user-images.githubusercontent.com/9977198/54713903-03849c00-4b50-11e9-8d99-83fe2e0cba7f.gif)

**Comment by PeterBowman** [comment]
Better to act than to think! Mentioned in https://github.com/asrob-uc3m/robotDevastation-playground/commit/c0fcd62d2f46ab640be248cf5a8d7a0bb0fd3fa4.
