### ISSUE TITLE
Think about Authors

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#110]
Currently hard-coded in main.cpp
We know better than that!

**Comment by jgvictores** [comment]
Slightly related: #99 and #100.

**Comment by PeterBowman** [comment]
Compare: [yarp/COPYING](https://github.com/robotology/yarp/blob/devel/COPYING) (more related to legal issues), [yarp/AUTHORS](https://github.com/robotology/yarp/blob/devel/AUTHORS) (old).

**Comment by jgvictores** [comment]
Blocked by #99

**Comment by PeterBowman** [comment]
Resolved at #117.
