### ISSUE TITLE
Some classes are unused

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#113]
I haven't been able to find any uses of [IniReader](https://github.com/asrob-uc3m/robotDevastation/blob/d4febd46391880b0c41e201c91921a2940e6af10/src/libraries/UtilsLib/IniReader.hpp), which was made when we were not depending on YARP for parsing `.ini` files.

**Comment by PeterBowman** [comment]
Also, the `number2str` free function from `Utils.hpp` could be easily inlined in code.

**Comment by PeterBowman** [comment]
Done at 10628cc.
