### ISSUE TITLE
Fix issues on http://asrob.uc3m.es/rddoc/todo.html

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#20]
Fix issues on http://asrob.uc3m.es/rddoc/todo.html, and drop use of @todo in favor of GitHub issues.

**Comment by David-Estevez** [comment]
I'm commenting here the issues to remove the need to go to doxygen to check them out:

### Class BasicImageManager
Move this class to RdImageLib, set it to be compiled only with the tests 

### Member rd::RdGameScreen::RdGameScreen ()
Fix this (to return something in case of error) 

### Class RdMockupImageEventListener
Move this class to RdImageLib, set it to be compiled only with the tests

**Comment by David-Estevez** [comment]
TODOs are now included in the repo as issues, closing this issue.

**Comment by jgvictores** [comment]
Look what the cat dragged in...  http://asrob.uc3m.es/rddoc/todo.html 😺

**Comment by David-Estevez** [comment]
That is under control, it was documented in #34. Therefore, I'm closing this issue again.
