### ISSUE TITLE
Easy stuff for dummies

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/robotDevastation#31]
This issue is pretended to have easy stuff for beginners that wants to start developing on robotDevastation. Also is posible to have an easy tag for that issue that are at an entry level ?

**Comment by David-Estevez** [comment]
I suggest creating a new repo called "robotDevastation-research" (or something similar) in which we research and develop apps related to augmented reality, tracking, etc that will be later incorporated to future versions of the main robotDevastation

**Comment by jgvictores** [comment]
+1 to "robotDevastation-research" !!

**Comment by David-Estevez** [comment]
Suggested lines:
* Add more cool robots to RobotDevastation:
    * https://github.com/bqlabs/loki
    * https://github.com/bqlabs/mizu
* Add AR interfaces:
    * http://www.slashgear.com/reality-editor-ar-app-connects-iot-devices-by-drawing-lines-15418452/
    * http://www.realityeditor.org
    * http://www.openhybrid.org/adding-object-and-marker.html
* Research about Game Engines:        
    * Unity
    * Unreal
    * [Ogre](http://www.ogre3d.org/)
    * [Irrlicht](http://irrlicht.sourceforge.net/)
    * [Crystal Space](http://www.crystalspace3d.org/main/Main_Page)

**Comment by jgvictores** [comment]
New repository created: https://github.com/asrob-uc3m/robotDevastation-research
