### ISSUE TITLE
Move debug objects to their respective internal libraries

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#34]
Move the following classes to their corresponding libraries, and set them to be compiled only with the tests (related to issue #21)
- Class **BasicImageManager** in _testRdImageManager.cpp_
  Move this class to RdImageLib, set it to be compiled only with the tests.
- Class **RdMockupImageEventListener** in _testRdYarpImageManager.cpp_
  Move this class to RdImageLib, set it to be compiled only with the tests.

**Comment by PeterBowman** [comment]
Done long time ago:

* `BasicImageManager` died tragically at 43fc09a
* `RdMockupImageEventListener` had been already ported to RdImageLib (now ImageLib) at the time of creation of this issue (¿?)

Link to current code and libraries: [src/libraries/ImageLib](https://github.com/asrob-uc3m/robotDevastation/tree/66b9551/src/libraries/ImageLib). Let's continue at #21 regarding what has to be compiled only with the tests.
