### ISSUE TITLE
Some docs are hidden in this repo

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#37]
We have some useful documentation hidden in the doc folder of this repo (e.g. FSM diagrams, main class diagram, what is each class for). I think we should move them to the wiki or doxygen in order to have as much documentation as possible in the same place.

**Comment by David-Estevez** [comment]
More hidden docs: http://asrob.uc3m.es/index.php/Robot_devastation_FSM

**Comment by jgvictores** [comment]
And (see [source](http://asrob.uc3m.es/index.php/Special:LonelyPages)): http://asrob.uc3m.es/index.php/Robot_Devastation:Development_Resources

**Comment by David-Estevez** [comment]
Buried docs are not available in the corresponding GitBook
