### ISSUE TITLE
robotDevastation not counting rdServer connect attempts correctly

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#39]
robotDevastation not counting rdServer connect attempts correctly. Should also add some info on number of attempt.

**Comment by David-Estevez** [comment]
Top the best of my knowledge, errors in connection are also not considered in the NetworkManager tests. They should be included in the test (an then fixed) to increase code cleanness and robustness.

**Comment by jgvictores** [comment]
@David-Estevez login() is tested in testRdYarpNetworkManager, which internally checks this connection, so the test is good.
robotDevastation, on the other hand, does not check the return value of login(). I'm going to fix this.
