### ISSUE TITLE
FSM integration in game

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#45]
Now that the FSM for the game is implemented, it needs to be integrated in the game (substituting old code).

**Comment by David-Estevez** [comment]
Behavior of RdYarpNetworkManager is not the same as MockupNetworkManager, so it has to be updated to match (so that the game can work).

**Comment by David-Estevez** [comment]
SDL stuff is now fixed (#52), game seems to fail once the login in the server has been performed.

**Comment by David-Estevez** [comment]
As FSM->start() is non-blocking, the program was performing cleanup just right after starting the FSM in the configure() method of robotDevastation module.

As the FSM has its own threads running, the main thread of the RFModule can be used to monitor the current state of the FSM, and to trigger cleanup when the FSM has arrived the end state.

**Comment by David-Estevez** [comment]
Done in a032880f5764a304e6d1e1d3a7f43e7f1b98a74b , but requires testing with the actual robot(s) in order to check that everything works as expected.

**Comment by David-Estevez** [comment]
Last time we checked, images were not being received correctly from the robot (only the first frame capture was being displayed). 

This requires more testing for validation.

**Comment by jgvictores** [comment]
Tested and working.
