### ISSUE TITLE
Create gitbook as User / Developer manual

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#47]
Create gitbook as User / Developer manual

**Comment by jgvictores** [comment]
- https://github.com/asrob-uc3m/robotDevastation-user-manual -> https://www.gitbook.com/book/asrob-uc3m/robotdevastation-user-manual
- https://github.com/asrob-uc3m/robotDevastation-developer-manual -> https://www.gitbook.com/book/asrob-uc3m/robotdevastation-developer-manual

**Comment by David-Estevez** [comment]
Juan says: Closed because they are created
