### ISSUE TITLE
Add Tests to Travis

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#49]
Add Tests to Travis

**Comment by jgvictores** [comment]
I've opened https://github.com/asrob-uc3m/robotDevastation-developer-manual/issues/1 on documenting what each test does in the Developer Manual.
Maybe this is overkill and should be done in doxygen?

**Comment by David-Estevez** [comment]
Could be interesting to know what tests are automated an which ones are manual

**Comment by David-Estevez** [comment]
Tests have been added, but not all of them work on travis. Errors should be checked to update the travis config file.

**Comment by jgvictores** [comment]
> Could be interesting to know what tests are automated an which ones are manual

With this we mean we should categorize tests:
- Which ones require physical robots
- Which ones require graphics
- Which ones can be run on Travis

**Comment by David-Estevez** [comment]
Now only automated tests are run by travis, but we have still errors related to #77 and #86. As the scope of this issue was to set the correct tests on travis, I'm closing this issue.

Tests are now documented [in the developer manual](https://asrob-uc3m.gitbooks.io/robotdevastation-developer-manual/content/en/tests.html), only in English at this moment.
