### ISSUE TITLE
Revive X-box controller control

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#5]
It was nice because the analog control could regulate speed.

**Comment by PeterBowman** [comment]
Mentioned in https://github.com/asrob-uc3m/robotDevastation-playground/commit/6a5b40ec04ed6cae0fff94f870ef070b1c4e6b6b, we'd need to split this into two subtasks:

- Create a new YARP analog input device (perhaps roboticslab-uc3m/yarp-devices).
- Integrate with RD (this repo).
