### ISSUE TITLE
Run without robot and with webcam for testing software

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#61]
While developing software, usually a robot is required to launch the Robot Devastation game for testing. But most of the time we are developing at home, or we have robots, but the batteries are dead.

I propose developing a simple virtual robot that works with a USB camera attached to the players PC and can be launched anywhere with no need for the actual robot, and the program should recognize it as a real robot.

**Comment by jgvictores** [comment]
I wouldn't call it a virtual robot... 🤔

**Comment by David-Estevez** [comment]
I'm open to a new name for this kind of robot.

**Comment by David-Estevez** [comment]
What I meant was a robot, similar to the example described in: http://asrob.uc3m.es/index.php/C%C3%B3mo_empezar_con_Robot_Devastation#Sin_robot but with images coming from the webcam.

**Comment by jgvictores** [comment]
Okay, I've changed the issue title to adjust to that.

**Comment by David-Estevez** [comment]
will you take care of this one?

**Comment by jgvictores** [comment]
I've self-assigned, but may need help as it involves mockupImageManager which I believe has changed since my original commits.

**Comment by jgvictores** [comment]
Finished at 6a6cfa96dd02a3bd06ccf8680455fab5ba1b56dd
Documented at http://asrob.uc3m.es/index.php/C%C3%B3mo_empezar_con_Robot_Devastation#Sin_robot_y_con_webcam_del_PC

**Comment by jgvictores** [comment]
This issue should remain open until PC local installation of used YARP `opencv_grabber` plugin is documented.

**Comment by jgvictores** [comment]
Finished at 8b8218fac76856456f6be40363c795a3f90c0b63
