### ISSUE TITLE
.travis.yml not updated to SDL2

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#77]
.travis.yml not updated to SDL2, must update.

**Comment by jgvictores** [comment]
Not as easy as https://github.com/asrob-uc3m/robotDevastation/commit/7dfac6c24150486b5f6f213827ea5f2de4cb60cc (see https://travis-ci.org/asrob-uc3m/robotDevastation/jobs/175587238 )

**Comment by PeterBowman** [comment]
I see two alternatives here:

* compile SDL2 from sources
* upgrade Travis host to trusty (beta): https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by PeterBowman** [comment]
Some progress was made with the second approach and [jobs/185271003](https://travis-ci.org/asrob-uc3m/robotDevastation/jobs/185271003).

**Comment by David-Estevez** [comment]
I think the approach you are working in is the most sensible one.

**Comment by PeterBowman** [comment]
Done in 8385e8d.

@jgvictores your commit has been cherry-picked in 48fa41c and merged into develop, you might want to delete the `issue-77-travis-sdl2` branch now.

**Comment by jgvictores** [comment]
@PeterBowman Yes, deleted the `issue-77-travis-sdl2` branch! Thanks as always!
