### ISSUE TITLE
Add --quiet flag to RdServer to disable stdout feedback

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#82]
Add --quiet flag to RdServer to disable stdout feedback. Use cases: mainly testing with the RdServer in a separate thread.

**Comment by PeterBowman** [comment]
Travis jobs currently [reach the maximum log size](https://travis-ci.org/asrob-uc3m/robotDevastation/jobs/214231734) because of `testYarpNetworkmanager` flooding with `rdServer` stdout (it runs on another thread). This idea could be considered for implementation in #87.

**Comment by David-Estevez** [comment]
Fixed by @PeterBowman, merged at  54e2ef4
