### ISSUE TITLE
Travis cannot build YARP

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#86]
As @PeterBowman discovered, YARP is not being built in Travis due to missing Eigen.

As far as I know, @PeterBowman is currently working to solve this.

**Comment by jgvictores** [comment]
We could also just remove `-DCREATE_LIB_MATH:BOOL=ON` from [where it is](https://github.com/asrob-uc3m/robotDevastation/blob/4668ca3d8f13975ca8a51e2bad6d8477b95a964c/.travis.yml#L43) as it's actually not even a requirement anymore.

**Comment by David-Estevez** [comment]
That is something @PeterBowman suggested yesterday, but neither of us knew for sure if LIB_MATH was still a requirement.

**Comment by jgvictores** [comment]
I'm pretty sure we can remove:
 `-DCREATE_GUIS:BOOL=ON`
`-DCREATE_LIB_MATH:BOOL=ON`
`-DENABLE_yarpcar_bayer_carrier:BOOL=ON`

Regarding carriers, we could activate something like:
`-DENABLE_yarpcar_mjpeg_carrier:BOOL=ON`
or simply forget about them by removing:
`-DCREATE_OPTIONAL_CARRIERS:BOOL=ON`

**Comment by PeterBowman** [comment]
You have to set -DCREATE_LIB_MATH:BOOL=OFF explicitly as it's enabled by default. I have to investigate it further, but I recall being unable to launch RD with this configuration.

**Comment by PeterBowman** [comment]
Done in f7c969e and merged into develop with 8385e8d.

See also #87.
