### ISSUE TITLE
Developer manual v1.0

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#88]
Progress:

* [x] Introduction
    * [x] What is Robot Devastation?
    * [x] Overview
* [x] Software
    * [x] Robot Devastation Overview
    * [x] Game FSM (+ flow diagram)
        * [x] Init State
        * [x] Game State
        * [x] Dead State
        * [x] Finite State Machine
    * [x] Sound Management
    * [x] Input Management
        * [x] Input Manager
        * [x] Listening to input events
        * [x] Creating input events
    * [x] Network Management
        * [x] Network Manager
        * [x] Listening to network events
    * [x] Robot Management
    * [x] User Interface Management
       * [x] Screen Manager
       * [x] Screens
    * [x] Camera Management
        * [x] Image Manager
        * [x]  Listening to Events
        * [x]  Processing the received images
    * [x] Data Management
        * [x]  Data Model
        * [x]  Mental Map
        * [x] Listening to Events
    * [x] Tests
* [x] Server
    * [x] Robot Devastation Server
    * [x] Network Protocol
* [x] Robots
    * [x] Rd Series
    * [x] Premium Series
* [x] How to contribute
* [x] Resources
* [x] Research

**Comment by jgvictores** [comment]
Maybe this should go... https://github.com/asrob-uc3m/robotDevastation-developer-manual/issues ?

**Comment by David-Estevez** [comment]
The Developer manual for v1.0 is finished, at last!
