### ISSUE TITLE
Add Unit Tests for each module currently developed

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#9]

**Comment by jgvictores** [comment]
This is important for the https://github.com/asrob-uc3m/robotDevastation/milestones/Add%20Unit%20Tests milestone (updated to new date). Commenting here just to bump on its relevance. I'd also like to point out there are at least two branches of work on this, namely:
* RdMockupImageManager (92f93b135305e0ad3e90dd05554169bc17d41994)
* RdMockupRobotManager (59a85fdaae33c2173afa1ec5267145b1928b2d3b)
Hope to render these out as soon as possible for merge.

**Comment by jgvictores** [comment]
Tests issue highly related with https://github.com/asrob-uc3m/robotDevastation/issues/6.

**Comment by David-Estevez** [comment]
With f49ccf74f288b5570207798d3b34e54da9133684 all modules, including Mockup objects, have unit tests
