### ISSUE TITLE
Race conditions in MockupState prevent tests to pass in travis

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation#92]
From [comment 1](https://github.com/asrob-uc3m/robotDevastation/issues/87#issuecomment-281780373):

> I had to put a sleep function at a1021b5 because of race conditions in https://travis-ci.org/asrob-uc3m/robotDevastation/jobs/204284401#L3631. @jgvictores suggests implementing `rd::MockupState` as a RPC responder (`yarp::os::PortReader` class).
>
>cc @David-Estevez

From [comment 2](https://github.com/asrob-uc3m/robotDevastation/issues/87#issuecomment-281788775):
> The failed Travis build linked earlier corresponds to a GCC job, whereas Clang showed positive results. *After* having put the sleep function, GCC runs nice, but now Clang is stuck in an infinite loop: https://travis-ci.org/asrob-uc3m/robotDevastation/jobs/204323228#L3968. Notice two failed assertions in previous lines, which may be the cause. We might want to find a more reliable solution than the current one.

**Comment by PeterBowman** [comment]
With quite a lot of help from @jgvictores, a RPC client-server model was implemented in `testFSM` and `MockupState` at 6b4757f. The build does not loop indefinitely and passes `testFSM` on both GCC and Clang jobs. I'll rewrite the branch and submit a patch for review in the next days.
