### ISSUE TITLE
C++ code cleanup

### ISSUE THREAD

**Issue by PeterBowman** [asrob-uc3m/robotDevastation#96]
This issue does not address a thorough review of code flow nor any programming structures. Simply put, I'd like to gather here a list of possible fixes that one may have noticed at a first glance during code development but never had the chance to properly focus on them:

- [x] prefixed header guards: `__DEAD_STATE_HPP__` -> `__RD_DEAD_STATE_HPP__` (d32aded)
- [x] `const` keyword in getters: `getName() const { ... }` (7dd2d68, 4e7d21d, 99c9d08)
- [x] pass object instances by `const` reference, if possible (7fee637, 83c6b46, 83ee9bf)
- [x] return `const` references to private members in class accessors (a344b9e)
- [x] provide trivial copy constructor and copy assignment operator for singleton classes (2272d97)
- [x] Doxygen documentation cleanup (67274fd, f77029a)
- [x] missing/superfluous `#include`s (be2a7de, e109550)
- [x] prefer `<cxxx>` headers to `<xxx.h>` (f3f14b6)
- [x] remove redundant `rd::` namespace qualifiers (39edd1e, 638bdc3)
- [x] remove uses of implied `this` pointer (11181f5)
- fix Eclipse and VC warnings:
  - [x] define missing virtual destructors (7180e05)
  - [x] initialize all members in class constructors (1434559, 99a54c2, 0855e17)
  - [x] VC: C4018 *mismatch between signed/unsigned values* et al. (752b3fa, ca4f4dc, 8bd7b45)
- [x] remove Emacs modelines? (TBD at asrob-uc3m/robotDevastation-developer-manual#4)

Please add your thoughts and expand the list if new candidate items are found.

**Comment by David-Estevez** [comment]
My bad, I wrote the wrong issue number in the commit message. Reopening issue :sweat_smile:

**Comment by PeterBowman** [comment]
Emacs modelines can be found in approx. 50% of C++ files in the `src` directory. YARP devs completely got rid of them about a year ago (robotology/yarp@f62d487). @jgvictores should we keep them around in RD code? Are they of any use, and if so, should we stamp them on the remaining half of source files?

**Comment by jgvictores** [comment]
Yes, I'm aware they removed them... I'm used to seeing them, but would be okay with their removal.

Their only use now is dictating tab/space convention, which would be much better placed in the [robotDevastation-developer-manual](https://github.com/asrob-uc3m/robotDevastation-developer-manual) (maybe you could put an issue there to remind us this?).
