### ISSUE TITLE
Determine project license

### ISSUE THREAD

**Issue by PeterBowman** [asrob-uc3m/robotDevastation#99]
Root `LICENSE` is a BSD-3-clause. Exported CMake configs and `main.cpp` files at `src/programs/` state that this is LGPL v2.1. Several CMake list files prefer GLP v2.0.

**Comment by jgvictores** [comment]
Yes, we should determine a license. For now:
- I've added some history at #100 (copyright->LGPL->BSD... :joy:).
- Our GPL seems to be only in `share`.
- We apparently do not link to any external GPL.
- I've been reading on [license switching](http://stackoverflow.com/questions/1409666/switching-license-from-gpl-to-bsd-in-later-time). Since we are few core developers, I expect we are not going to have any issues for agreeing, so transition will run smoothly.

**Comment by PeterBowman** [comment]
* https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
* https://www.quora.com/What-are-the-major-differences-between-GNU-LGPL-v3-and-v2-1

**Comment by jgvictores** [comment]
Ok `LGPL v2.1`?

**Comment by David-Estevez** [comment]
@smorante  agrees with LPGL v2.1, what changes need to be done?

**Comment by David-Estevez** [comment]
![image](https://cloud.githubusercontent.com/assets/1451819/25195121/e2cce80e-253c-11e7-9088-fd1147a70717.png)

**Comment by PeterBowman** [comment]
Let me drop this here regarding copyright notices on top of each source file:

http://lu.is/blog/2012/03/17/on-the-importance-of-per-file-license-information/

**Comment by jgvictores** [comment]
+1 to adding copyright notices (license, author(s) or at least something ASROB) on top of each source file.

Not sure if it's stated in the article, but the fact is many times it's noobs who don't worry about licenses they're unaware about, and just copy and paste files. Adding 1-2 header lines can increase traceability of where and how our files are being used, which is definitely a plus.

**Comment by PeterBowman** [comment]
I've just found this article which favours GPL over LGPL licenses:

https://www.gnu.org/licenses/why-not-lgpl.html

**Comment by jgvictores** [comment]
GNU are a bit (legitimately) biased towards GPL. :smile:
LGPL has the benefit of not scaring off potential industry partners, while still promoting them to improve whatever set of core libraries we provide.

**Comment by jgvictores** [comment]
Need:
1. Templates for new uniform headers (for c++, cmake). 
1. Script (possibly python) for incorporating this uniform header in files.

**Comment by jgvictores** [comment]
```
* Authors: See https://github.com/asrob-uc3m/robotDevastation/blob/master/AUTHORS.md
* CopyPolicy: Released under the terms of the LGPLv2.1, see https://github.com/asrob-uc3m/robotDevastation/blob/master/LICENSE
 ```

**Comment by jgvictores** [comment]
```
* Authors: See AUTHORS.md at project root.
* CopyPolicy: Released under the terms of the LGPLv2.1, see LICENSE at project root.
* URL: https://github.com/asrob-uc3m/robotDevastation
 ```

**Comment by PeterBowman** [comment]
See also *How to Apply These Terms to Your New Libraries* at:

https://github.com/github/choosealicense.com/blob/7213ccf/_licenses/lgpl-2.1.txt#L494-L538

**Comment by PeterBowman** [comment]
Resolved at #117.

**Comment by PeterBowman** [comment]
Strangely enough, we actually forgot to update the LICENSE file itself. Done at 99f5d02 (and I've just forgotten to [skip ci], yay!).

**Comment by jgvictores** [comment]
No problem LOL!
